export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
//theme
import 'primeflex/primeflex.css';
import "primereact/resources/themes/lara-light-indigo/theme.css";     
    
//core
import "primereact/resources/primereact.min.css";   
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
